config/routes.rb
Dispo::Application.routes.draw do

  namespace :android do
    resources :tokens, :only => [:create, :destroy]
    resources :http_requests do
      collection do
        get 'getTermine'
        post 'getTermine'
        get 'postAuftragsabschluss'
        post 'postAuftragsabschluss'
      end
    end
  end

  namespace :purchase do resources :storages end

  resources :s3_uploads

  devise_for :users, :path_prefix=>"d", :controllers=> {:sessions=>"sessions"}

  resources :bugtrackers, :only => [:new, :create]
  resources :users, :except => [:destroy, :create, :index]
  resources :plz
  resources :cities
  resources :streets
  resources :street_numbers

  match '/purchase', :controller => 'purchase/base', :action => 'index'
  match '/scheduling', :controller => 'scheduling/base', :action => 'index'
  match '/scheduling_leader', :controller => 'scheduling_leader/base', :action => 'index'
  match '/management', :controller => 'management/base', :action => 'index'
  match '/management/reports', :controller => 'management/reports', :action => 'index'
  match '/management/reports/overview_performance_appointments', :controller => 'management/reports', :action => 'overview_performance_appointments'
  match '/management/reports/overview_performance_success', :controller => 'management/reports', :action => 'overview_performance_success'
  match '/management/reports/overview_dispositions', :controller => 'management/reports', :action => 'overview_dispositions'

  match '/management/reports/crp', :controller => 'management/reports', :action => 'capacity_requirements_planning'
  match '/service', :controller => 'service/base', :action => 'index'
  match '/accounting', :controller => 'accounting/base', :action => 'index'
  match '/admin', :controller => 'admin/base', :action => 'index'
  match '/admin/delayed_jobs', :controller => 'admin/delayed_jobs', :action => 'index'
  match '/mobile', :controller => 'mobile/base', :action => 'index'
  match '/test', :controller => 'test/base', :action => 'index'
  match '/test/sig1', :controller => 'test/base', :action => 'sig1'
  match '/test/sig2', :controller => 'test/base', :action => 'sig2'
  match '/test/sig3', :controller => 'test/base', :action => 'sig3'
  match '/test/sig4', :controller => 'test/base', :action => 'sig4'
  match '/test/sig5', :controller => 'test/base', :action => 'sig5'
  match '/test/sig6', :controller => 'test/base', :action => 'sig6'
  match '/test/sig7', :controller => 'test/base', :action => 'sig7'
  match '/test/pdf', :controller => 'test/base', :action => 'pdf'

  match '/no_right', :controller => 'base', :action => 'no_right'
  match '/issue_form', :controller => 'base', :action => 'issue_form'

  root :to => "base#index"

  namespace :admin do
    resources :bugtrackers do
      collection do
        get 'reload_index'
      end
    end
    resources :logs
    resources :service_completions
    resources :transfer_points
    resources :service_jobs do
      resources :service_appointments
      resources :service_completions
      resources :service_comments
    end
    resources :service_appointments
    resources :service_completions
    resources :photos
    resources :special_expenses
    resources :jobs do
      resources :appointments
      resources :cancellations
      resources :appointment_requests
      resources :completions
    end
    resources :appointments do
      member do
        get 'special_expenses_pop_up'
      end
      resources :special_expenses
    end
    resources :users do
      collection do
        get 'new_shortcut'
        post 'create_shortcut'
        get 'advanced_search'
        post 'advanced_search'
      end
    end
    resources :service_users
    resources :service_user_groups do
      member do
        get 'appointments'
        get 'appointments_data'
      end
    end
    resources :scheduling_users
    resources :clients
    resources :job_types
    resources :fi_fuse_types
    resources :building_types
    resources :network_types
    resources :modem_types
    resources :waiting_causes
    resources :cancellations
    resources :appointment_requests
    resources :completions do
      member do
        get 'pdf'
        get 'get_zip'
      end
    end
  end
  match '/admin/import_jobs', :controller => 'admin/base', :action => 'import_jobs'
  match '/admin/import_jobs_from_text', :controller => 'admin/base', :action => 'import_jobs_from_text'
  match '/admin/create_jobs_from_text', :controller => 'admin/base', :action => 'create_jobs_from_text'

  match '/admin/import_service_jobs_from_text', :controller => 'admin/base', :action => 'import_service_jobs_from_text'
  match '/admin/create_service_jobs_from_text', :controller => 'admin/base', :action => 'create_service_jobs_from_text'

  match '/admin/import_job', :controller => 'admin/base', :action => 'import_job'
  match '/admin/create_job', :controller => 'admin/base', :action => 'create_job'

  namespace :accounting do
  end

  namespace :scheduling_leader do
    resources :automatic_workflow_items
    resources :transfer_points
    resources :clients
    resources :scheduling_user_groups
    resources :service_user_groups do
      member do
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
      end
    end
    resources :jobs, :only => [:show, :index] do
      resources :comments
      resources :appointments, :except => [:destroy]
    end
    resources :completions
    resources :appointments, :except => [:destroy] do
      collection do
        get 'open'
        get 'calendar'
        get 'pop_up'
        get 'data'
        get 'latest_update'
      end
    end
    resources :appointment_requests
    resources :cancellations
    resources :users, :controller => 'service_users', :only => [:show]
    resources :scheduling_users, :except => [:destroy]
    resources :days_of_absence
    resources :service_users, :except => [:destroy] do
      resources :days_of_absence
      member do
        get 'create_pdf'
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
        get 'get_days_of_absence'
      end
      collection do
        get 'show_send_emails'
      end
    end

    resources :user do
      resources :days_of_absence do
      end
    end
  end
  match '/scheduling_leader/service_user_groups/:id/appointments/pop_up', :controller => 'scheduling_leader/service_user_groups', :action => 'appointments_pop_up'
  match '/scheduling_leader/import_job', :controller => 'scheduling_leader/base', :action => 'import_job'
  match '/scheduling_leader/create_job', :controller => 'scheduling_leader/base', :action => 'create_job'
  match '/scheduling_leader/service_users/send_emails', :controller => 'scheduling_leader/service_users', :action => 'send_emails'
  match '/scheduling_leader/import_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'import_jobs_from_text'
  match '/scheduling_leader/create_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'create_jobs_from_text'
  match '/scheduling_leader/import_service_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'import_service_jobs_from_text'
  match '/scheduling_leader/create_service_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'create_service_jobs_from_text'
  match '/scheduling_leader/quotes_per_controller', :controller => 'scheduling_leader/base', :action => 'quotes_per_controller'
  match '/scheduling_leader/volume_per_controller', :controller => 'scheduling_leader/base', :action => 'volume_per_controller'

  namespace :scheduling do
    resources :service_completions, :except => [:destroy] do
      member do
        get 'pdf'
        get 'get_zip'
      end
    end
    resources :service_jobs do
      resources :service_appointments
      resources :service_completions
      resources :service_comments
      collection do
        get 'all'
        get 'closed'
      end
      member do
        get 'close'
      end
    end
    resources :service_appointments do
      member do
        get 'create_pdf'
        get 'mail_pdf'
      end
    end
    resources :transfer_points
    resources :special_expenses
    resources :cancellations
    resources :completions, :except => [:destroy] do
      member do
        get 'technician_signature'
        get 'pdf'
        get 'get_zip'
      end
    end
    resources :appointment_requests, :except => [:destroy]
    resources :jobs, :except => [:destroy] do
      resources :comments
      resources :appointments, :except => [:destroy]
      collection do
        get 'all'
        get 'closed'
        get 'all_closed'
      end
      member do
        get 'close'
      end
    end
    resources :appointments do
      collection do
        get 'open'
        get 'calendar'
        get 'calendar_data'
        post 'calendar_data'
        get 'pop_up'
        get 'data'
        get 'latest_update'
        post 'save_calendar_position'
        post 'save_new_calendar_task'
        post 'get_job_id'
      end
      resources :special_expenses
      member do
        get 'create_pdf'
        get 'mail_pdf'
        get 'has_special_expenses'
        get 'update_from_js'
      end
    end
    resources :users, :controller => 'service_users'
    resources :service_users, :except => [:destroy, :edit, :new] do
      member do
        get 'mail_appointments_list'
        get 'mail_tomorrow_appointments_forms'
        get 'create_pdf'
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
      end
    end
    resources :user do
      resources :days_of_absence do
      end
    end

    resources :service_user_groups do
      member do
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
      end
    end
  end

app/models/job_type.rb
class JobType < ActiveRecord::Base
	validates :name, :presence => {:message => "^Geben Sie eine Bezeichnung an."}
  scope :active, where(:active => true)

  def self.options_for_select
    active.collect {|c| [ c.name, c.id ] }
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < JobsController

end

app/controllers/jobs_controller.rb
# encoding: utf-8
class JobsController < InheritedResources::Base
  caches_action :index# , :cache_path => Proc.new { |controller| controller.params.to_s + current_user.client_names }
  caches_action :show, :edit

  cache_sweeper :job_sweeper, :only => [:create, :update, :destroy]
  def index
    @search = Job.search(params[:q])
    @jobs = @search.result.belonging_to_user_client(current_user).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    #@jobs = Job.ot_auftragsnummer_like(params[:ot_auftragsnummer]).workorder_like(params[:workorder]).mandant_id_like(params[:mandant_id]).kunde_plz_like(params[:kunde_plz]).kunde_ort_like(params[:kunde_ort]).kunde_strasse_like(params[:kunde_strasse]).kunde_hausnummer_like(params[:kunde_hausnummer]).kunde_nachname_like(params[:kunde_nachname]).kunde_vorname_like(params[:kunde_vorname]).kunde_plz_like(params[:kunde_kundennummer]).eigentuemer_nachname_like(params[:eigentuemer_nachname]).eigentuemer_vorname_like(params[:eigentuemer_vorname]).order(sort_column + " " + sort_direction).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    #@jobs = Job.where("ot_auftragsnummer LIKE '%#{params[:ot_auftragsnummer]}%'").where("kunde_plz LIKE '%#{params[:kunde_plz]}%'").where("kunde_ort LIKE '%#{params[:kunde_ort]}%'").where("kunde_strasse LIKE '%#{params[:kunde_strasse]}%'").where("kunde_hausnummer LIKE '%#{params[:kunde_hausnummer]}%'").where("kunde_nachname LIKE '%#{params[:kunde_nachname]}%'").where("kunde_vorname LIKE '%#{params[:kunde_vorname]}%'").where("kunde_kundennummer LIKE '%#{params[:kunde_kundennummer]}%'").where("eigentuemer_nachname LIKE '%#{params[:eigentuemer_nachname]}%'").where("eigentuemer_vorname LIKE '%#{params[:eigentuemer_vorname]}%'").order(sort_column + " " + sort_direction).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    #@jobs = Job.order(sort_column + " " + sort_direction).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    render :layout => "application"
  end

  def show
    @job = Job.find(params[:id])
    @other_jobs_in_object = get_other_jobs_in_object(@job)
    #expire_action(:controller => 'admin/jobs', :action => 'show', :id => params[:id])
    #fresh_when(:etag => @job, :last_modified => @job.updated_at.utc, :public => false) unless (Rails.env == "development")
  end

  def edit
    @job = Job.find(params[:id])
    @other_jobs_in_object = get_other_jobs_in_object(@job)
    #fresh_when(:etag => @job, :last_modified => @job.updated_at.utc, :public => false) unless (Rails.env == "development")
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      redirect_to([current_view, :jobs], :notice => 'Auftrag erstellt: '+ self.class.helpers.link_to(@job.short_description, url_for([current_view, @job])))
    else
      render :action => "new"
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to([current_view, @job], :notice => 'Auftrag upgedated: '+ self.class.helpers.link_to(@job.short_description, url_for([current_view, @job])))
    else
      render :action => "edit"
    end
  end

  def destroy
    @job = Job.find(params[:id])
    if @job.destroy
      notice = 'Auftrag gelöscht.'
    else
      notice = "Unsuccessfully destroyed."
    end
    redirect_to([current_view, :jobs], :notice => notice)
  end

  def new
    @job = Job.new
    @job.client = current_user.clients.first
  end

  private

  def get_other_jobs_in_object(job)
    Job.where(:kunde_plz => job.kunde_plz).where(:kunde_ort => job.kunde_ort).where(:kunde_strasse => job.kunde_strasse).where(:kunde_hausnummer => job.kunde_hausnummer).where("id != "+job.id.to_s)
  end


end

app/controllers/management/jobs_controller.rb
class Management::JobsController < JobsController
end

app/controllers/scheduling_leader/jobs_controller.rb
class SchedulingLeader::JobsController < JobsController
  actions :index, :new, :create, :show, :edit, :update
  before_filter :get_job_count_by_status

  def review
    @job = Job.find(params[:id])
    render :layout => "pop_up"
  end

  def index
    @search = Job.search(params[:q])
    @jobs = @search.result.where(:client_id => current_user.clients.collect{|c|c.id}).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    render :layout => "application"
  end

  def closed
    @closed_jobs = Job.where(:status => 3).where(:client_id => current_user.clients.collect{|c|c.id}).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    @cancelled_jobs = Job.where(:status => 5).where(:client_id => current_user.clients.collect{|c|c.id}).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    render :layout => "application"
  end

  def close
    @job = Job.find(params[:id])
    @job.status = 4
    @job.closed = true
    @job.save 
    redirect_to :action => "closed"
  end
    
  def show
    @job = Job.find(params[:id])
    @other_jobs_in_object = get_other_jobs_in_object(@job)
#    #fresh_when(:etag => @job, :last_modified => @job.updated_at.utc, :public => false) unless (Rails.env == "development")
  end

  def edit
    @job = Job.find(params[:id])
    @other_jobs_in_object = get_other_jobs_in_object(@job)
 #   #fresh_when(:etag => @job, :last_modified => @job.updated_at.utc, :public => false) unless (Rails.env == "development")
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      redirect_to(scheduling_job_path(@job), :notice => 'Auftrag erstellt: '+self.class.helpers.link_to(@job.short_description, scheduling_job_path(@job)))
    else
      render :action => "new"
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to(scheduling_jobs_path(@job), :notice => 'Auftrag upgedated: '+ self.class.helpers.link_to(@job.short_description, scheduling_job_path(@job)))        
    else
      render :action => "edit"
    end
  end

  private 
    def get_other_jobs_in_object(job)
      Job.where(:kunde_plz => job.kunde_plz).where(:kunde_ort => job.kunde_ort).where(:kunde_strasse => job.kunde_strasse).where(:kunde_hausnummer => job.kunde_hausnummer).where("id != "+job.id.to_s)
    end
end

app/controllers/service/jobs_controller.rb
class Service::JobsController < JobsController
  actions :index, :show

  def index
    @search = Job.joins{appointments}.where{(status != 1)}.where("appointments.user_id" => current_user.id).search(params[:search])
    @jobs = @search.result.paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]

    @service_search = ServiceJob.joins{service_appointment}.where{(status != 1)}.where("service_appointments.user_id" => current_user.id).search(params[:search])
    @service_jobs = @service_search.result.paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    render :layout => "application"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
	def status_name(status)
		return "zu disponieren" if (status == 0)
		return "disponiert" if (status == 1)
		return "wartend" if (status == 2)
		return "abgeschlossen" if (status == 3)
		return "technisch abgeschlossen" if (status == 4)
		return "storniert" if (status == 5)
	end
end

app/views/admin/jobs/_sub_menu.html.erb
<li class="first <%= params[:action]  == 'index' ? 'active' : '' %>"><%= link_to "Alle Installationsaufträge", admin_jobs_path %></li>
<li class="<%= params[:action] == 'new' ? 'active' : '' %>"><%= link_to "Neuen Auftrag anlegen", new_admin_job_path %></li>
<% if params[:action] == 'edit' then %>
<li class="active"><%= link_to "Auftrag bearbeiten", edit_admin_job_path %></li>
<% end %>
<% if params[:action] == 'show' then %>
<li class="active"><%= link_to "Auftragsansicht", admin_job_path %></li>
<% end %>

app/views/admin/jobs/closed.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">Abgeschlossene Aufträge</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first" style="width:150px">OT-Nummer</th>
          <th>PLZ</th>
          <th>Ort</th>
          <th>Straße</th>
          <th>Hausnummer</th>
          <th>Nachname</th>
          <th>Vorname</th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @closed_jobs.each do |job| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= job.ot_auftragsnummer %>
          </td>
          <td>
            <%= job.kunde_plz %>
          </td>
          <td>
            <%= job.kunde_ort %>
          </td>
          <td>
            <%= job.kunde_strasse %>
          </td>
          <td>
            <%= job.kunde_hausnummer %>
          </td>
          <td>
            <%= job.kunde_nachname %>
          </td>
          <td>
            <%= job.kunde_vorname %>
          </td>
          <td class="last">
            <%= link_to image_tag("/assets/icons/show.png", :title=>"Anzeigen", :alt=>"Anzeigen"), admin_job_path(job) %>
            <%= link_to image_tag("/assets/icons/edit.png", :title=>"Bearbeiten", :alt=>"Bearbeiten"), edit_admin_job_path(job) %>
            <%= link_to image_tag("/assets/icons/cross.png", :title=>"Löschen", :alt=>"Löschen"), admin_job_path(job), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Wirklich löschen?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <%= page_entries_info @closed_jobs %><br/><br/><br/>
      <%= will_paginate @closed_jobs %><br/><br/><br/>
    </div>
  </div>
</div>

app/views/admin/jobs/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Auftrag bearbeiten</h2>
    <div class="inner">
      <%= form_for @job, :url => admin_job_path(@job), :html => { :class => :form } do |f| -%>
        <%= render :partial => "general/job_form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/admin/jobs/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Alle Installationsaufträge</h2>
    <div class="inner">

    <%= search_form_for @search, :url => admin_jobs_path do |f| %>
     <%= render :partial => "jobs/jobs_filter_panel", :locals => {:f => f, :status_closed => false} %>
      <div id="jobs"><%= render :partial => "general/jobs_table", :locals => {:jobs => @jobs} %></div>
    <% end %>
    </div>
  </div>
</div>


<%= content_for :bottom do %>
<script type="text/javascript">
/*
$(function() {
  $("#jobs th a, #jobs .pagination a").live("click", function(){
    $.getScript(this.href);
    return false;
  });

  $("#jobs_search").keyup(function(){
    $.get($("#jobs_search").attr("action"), $("#jobs_search").serialize(), null, "script");
    return false;
  });

});
*/
</script>
<% end %>

app/views/admin/jobs/index.js.erb
$("#jobs").html("<%= escape_javascript(render("jobs")) %>")

app/views/admin/jobs/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Neuer Auftrag</h2>
    <div class="inner">
      <%= form_for :job, :url => admin_jobs_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "general/job_form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/admin/jobs/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Auftragsansicht: <%= @job.short %> </h2>
    <div class="inner">
      <%= render "button_bar" %>
      <%= form_for @job, :url => [current_view, @job], :html => { :class => :form } do |f| -%>
        <%= render :partial => "general/job_form", :locals => {:f => f, :disabled => true} %>
      <% end -%>
      <%= render "button_bar" %> 
    </div>
  </div>
</div>