config/routes.rb
Dispo::Application.routes.draw do

  namespace :android do
    resources :tokens, :only => [:create, :destroy]
    resources :http_requests do
      collection do
        get 'getTermine'
        post 'getTermine'
        get 'postAuftragsabschluss'
        post 'postAuftragsabschluss'
      end
    end
  end

  namespace :purchase do resources :storages end

  resources :s3_uploads

  devise_for :users, :path_prefix=>"d", :controllers=> {:sessions=>"sessions"}

  resources :bugtrackers, :only => [:new, :create]
  resources :users, :except => [:destroy, :create, :index]
  resources :plz
  resources :cities
  resources :streets
  resources :street_numbers

  match '/purchase', :controller => 'purchase/base', :action => 'index'
  match '/scheduling', :controller => 'scheduling/base', :action => 'index'
  match '/scheduling_leader', :controller => 'scheduling_leader/base', :action => 'index'
  match '/management', :controller => 'management/base', :action => 'index'
  match '/management/reports', :controller => 'management/reports', :action => 'index'
  match '/management/reports/overview_performance_appointments', :controller => 'management/reports', :action => 'overview_performance_appointments'
  match '/management/reports/overview_performance_success', :controller => 'management/reports', :action => 'overview_performance_success'
  match '/management/reports/overview_dispositions', :controller => 'management/reports', :action => 'overview_dispositions'

  match '/management/reports/crp', :controller => 'management/reports', :action => 'capacity_requirements_planning'
  match '/service', :controller => 'service/base', :action => 'index'
  match '/accounting', :controller => 'accounting/base', :action => 'index'
  match '/admin', :controller => 'admin/base', :action => 'index'
  match '/admin/delayed_jobs', :controller => 'admin/delayed_jobs', :action => 'index'
  match '/mobile', :controller => 'mobile/base', :action => 'index'
  match '/test', :controller => 'test/base', :action => 'index'
  match '/test/sig1', :controller => 'test/base', :action => 'sig1'
  match '/test/sig2', :controller => 'test/base', :action => 'sig2'
  match '/test/sig3', :controller => 'test/base', :action => 'sig3'
  match '/test/sig4', :controller => 'test/base', :action => 'sig4'
  match '/test/sig5', :controller => 'test/base', :action => 'sig5'
  match '/test/sig6', :controller => 'test/base', :action => 'sig6'
  match '/test/sig7', :controller => 'test/base', :action => 'sig7'
  match '/test/pdf', :controller => 'test/base', :action => 'pdf'

  match '/no_right', :controller => 'base', :action => 'no_right'
  match '/issue_form', :controller => 'base', :action => 'issue_form'

  root :to => "base#index"

  namespace :admin do
    resources :bugtrackers do
      collection do
        get 'reload_index'
      end
    end
    resources :logs
    resources :service_completions
    resources :transfer_points
    resources :service_jobs do
      resources :service_appointments
      resources :service_completions
      resources :service_comments
    end
    resources :service_appointments
    resources :service_completions
    resources :photos
    resources :special_expenses
    resources :jobs do
      resources :appointments
      resources :cancellations
      resources :appointment_requests
      resources :completions
    end
    resources :appointments do
      member do
        get 'special_expenses_pop_up'
      end
      resources :special_expenses
    end
    resources :users do
      collection do
        get 'new_shortcut'
        post 'create_shortcut'
        get 'advanced_search'
        post 'advanced_search'
      end
    end
    resources :service_users
    resources :service_user_groups do
      member do
        get 'appointments'
        get 'appointments_data'
      end
    end
    resources :scheduling_users
    resources :clients
    resources :job_types
    resources :fi_fuse_types
    resources :building_types
    resources :network_types
    resources :modem_types
    resources :waiting_causes
    resources :cancellations
    resources :appointment_requests
    resources :completions do
      member do
        get 'pdf'
        get 'get_zip'
      end
    end
  end
  match '/admin/import_jobs', :controller => 'admin/base', :action => 'import_jobs'
  match '/admin/import_jobs_from_text', :controller => 'admin/base', :action => 'import_jobs_from_text'
  match '/admin/create_jobs_from_text', :controller => 'admin/base', :action => 'create_jobs_from_text'

  match '/admin/import_service_jobs_from_text', :controller => 'admin/base', :action => 'import_service_jobs_from_text'
  match '/admin/create_service_jobs_from_text', :controller => 'admin/base', :action => 'create_service_jobs_from_text'

  match '/admin/import_job', :controller => 'admin/base', :action => 'import_job'
  match '/admin/create_job', :controller => 'admin/base', :action => 'create_job'

  namespace :accounting do
  end

  namespace :scheduling_leader do
    resources :automatic_workflow_items
    resources :transfer_points
    resources :clients
    resources :scheduling_user_groups
    resources :service_user_groups do
      member do
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
      end
    end
    resources :jobs, :only => [:show, :index] do
      resources :comments
      resources :appointments, :except => [:destroy]
    end
    resources :completions
    resources :appointments, :except => [:destroy] do
      collection do
        get 'open'
        get 'calendar'
        get 'pop_up'
        get 'data'
        get 'latest_update'
      end
    end
    resources :appointment_requests
    resources :cancellations
    resources :users, :controller => 'service_users', :only => [:show]
    resources :scheduling_users, :except => [:destroy]
    resources :days_of_absence
    resources :service_users, :except => [:destroy] do
      resources :days_of_absence
      member do
        get 'create_pdf'
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
        get 'get_days_of_absence'
      end
      collection do
        get 'show_send_emails'
      end
    end

    resources :user do
      resources :days_of_absence do
      end
    end
  end
  match '/scheduling_leader/service_user_groups/:id/appointments/pop_up', :controller => 'scheduling_leader/service_user_groups', :action => 'appointments_pop_up'
  match '/scheduling_leader/import_job', :controller => 'scheduling_leader/base', :action => 'import_job'
  match '/scheduling_leader/create_job', :controller => 'scheduling_leader/base', :action => 'create_job'
  match '/scheduling_leader/service_users/send_emails', :controller => 'scheduling_leader/service_users', :action => 'send_emails'
  match '/scheduling_leader/import_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'import_jobs_from_text'
  match '/scheduling_leader/create_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'create_jobs_from_text'
  match '/scheduling_leader/import_service_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'import_service_jobs_from_text'
  match '/scheduling_leader/create_service_jobs_from_text', :controller => 'scheduling_leader/base', :action => 'create_service_jobs_from_text'
  match '/scheduling_leader/quotes_per_controller', :controller => 'scheduling_leader/base', :action => 'quotes_per_controller'
  match '/scheduling_leader/volume_per_controller', :controller => 'scheduling_leader/base', :action => 'volume_per_controller'

  namespace :scheduling do
    resources :service_completions, :except => [:destroy] do
      member do
        get 'pdf'
        get 'get_zip'
      end
    end
    resources :service_jobs do
      resources :service_appointments
      resources :service_completions
      resources :service_comments
      collection do
        get 'all'
        get 'closed'
      end
      member do
        get 'close'
      end
    end
    resources :service_appointments do
      member do
        get 'create_pdf'
        get 'mail_pdf'
      end
    end
    resources :transfer_points
    resources :special_expenses
    resources :cancellations
    resources :completions, :except => [:destroy] do
      member do
        get 'technician_signature'
        get 'pdf'
        get 'get_zip'
      end
    end
    resources :appointment_requests, :except => [:destroy]
    resources :jobs, :except => [:destroy] do
      resources :comments
      resources :appointments, :except => [:destroy]
      collection do
        get 'all'
        get 'closed'
        get 'all_closed'
      end
      member do
        get 'close'
      end
    end
    resources :appointments do
      collection do
        get 'open'
        get 'calendar'
        get 'calendar_data'
        post 'calendar_data'
        get 'pop_up'
        get 'data'
        get 'latest_update'
        post 'save_calendar_position'
        post 'save_new_calendar_task'
        post 'get_job_id'
      end
      resources :special_expenses
      member do
        get 'create_pdf'
        get 'mail_pdf'
        get 'has_special_expenses'
        get 'update_from_js'
      end
    end
    resources :users, :controller => 'service_users'
    resources :service_users, :except => [:destroy, :edit, :new] do
      member do
        get 'mail_appointments_list'
        get 'mail_tomorrow_appointments_forms'
        get 'create_pdf'
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
      end
    end
    resources :user do
      resources :days_of_absence do
      end
    end

    resources :service_user_groups do
      member do
        get 'appointments'
        get 'appointments_pop_up'
        get 'appointments_data'
      end
    end
  end

app/models/service_user_group.rb
class ServiceUserGroup < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :postal_codes
	belongs_to :client
	validates :name, :presence => {:message => "^Geben Sie eine Bezeichnung an."}

	def postal_codes_csv
		postal_codes.collect {|postal_code| postal_code.code }.sort().join(", ") 
	end

	def self.available_service_users_for(controller)
	 	available_service_users = Array.new
	    Client.is_assigned_to_user(controller).each do |client|
	      client.users.service.where(:active => true).each do |user| 
	        available_service_users << user
	      end
	    end 
	    return available_service_users.uniq
	end

	def self.belonging_to_user_client(user)
		self.where(:client_id => user.clients.collect{|c|c.id})
	end
end

app/controllers/admin/service_user_groups_controller.rb
# encoding: utf-8
class Admin::ServiceUserGroupsController < ServiceUserGroupsController
  
end

app/controllers/scheduling/service_user_groups_controller.rb
# encoding: utf-8
class Scheduling::ServiceUserGroupsController < ServiceUserGroupsController
  	before_filter :get_job_count_by_status
end

app/controllers/scheduling_leader/service_user_groups_controller.rb
# encoding: utf-8
class SchedulingLeader::ServiceUserGroupsController < ServiceUserGroupsController
  	before_filter :get_job_count_by_status
end

app/controllers/service_user_groups_controller.rb
# encoding: utf-8
class ServiceUserGroupsController < InheritedResources::Base
  #caches_action :show, :edit

  def index
    @search = ServiceUserGroup.search(params[:q])
    if params[:q] && params[:q][:s] && params[:q][:s].include?("user")
      @service_user_groups = ServiceUserGroup.joins('LEFT JOIN "service_user_groups_users"  ON "service_user_groups"."id" = "service_user_groups_users"."service_user_group_id"  LEFT JOIN "users" ON "service_user_groups_users.user_id" = "users.id"').belonging_to_user_client(User.first).order(params[:q][:s].sub("user","users.vorname")).order(params[:q][:s].sub("user","users.nachname")).uniq!
      @service_user_groups = @service_user_groups.paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    else
      @service_user_groups = @search.result.belonging_to_user_client(current_user).paginate :per_page => Settings.DEFAULT_ITEMS_PER_TABLE, :page => params[:page]
    end
    
    render "service_user_groups/index"
  end

  def new
    @service_user_group = ServiceUserGroup.new
    render "service_user_groups/new"
  end

  def show
    @service_user_group = ServiceUserGroup.belonging_to_user_client(current_user).find(params[:id])
    render "service_user_groups/show"
  end

  def edit
    @service_user_group = ServiceUserGroup.belonging_to_user_client(current_user).find(params[:id])
    render "service_user_groups/edit"
  end
  
  def appointments
    @service_user_group = ServiceUserGroup.belonging_to_user_client(current_user).find(params[:id])
    render "service_user_groups/appointments"
  end

  def appointments_pop_up
    @service_user_group = ServiceUserGroup.belonging_to_user_client(current_user).find(params[:id])
    render "service_user_groups/appointments_pop_up", :layout => "pop_up"
  end

  def appointments_data
    @service_user_group = ServiceUserGroup.belonging_to_user_client(current_user).find(params[:id])
    render "service_user_groups/appointments_data", :layout => false
  end
 
  def create
    @service_user_group = ServiceUserGroup.new(params[:service_user_group])
    postal_codes = params[:postal_codes_csv][0].split(",")
    postal_codes.each do |c|
      pc = PostalCode.where(:code => c)
      if (pc.blank?) then
        pc = PostalCode.new
        pc.code = c.strip
        pc.save
      end
      @service_user_group.postal_codes << pc
    end
    if @service_user_group.save
      redirect_to([current_view, :service_user_groups], :notice => 'Technikergruppe erstellt: ' + self.class.helpers.link_to(@service_user_group.name, admin_service_user_group_path(@service_user_group)))
    else
      render :action => "new"
    end
  end

  def update
    params[:service_user_group][:user_ids] ||= []
    @service_user_group = ServiceUserGroup.belonging_to_user_client(current_user).find(params[:id])
    @service_user_group.postal_codes.clear()
    postal_codes = params[:postal_codes_csv][0].split(",")
    postal_codes.each do |c|
      pc = PostalCode.where(:code => c)
      if (pc.blank?) then
        pc = PostalCode.new
        pc.code = c.strip
        pc.save
      end
      @service_user_group.postal_codes << pc
    end

    if @service_user_group.update_attributes(params[:service_user_group])
      #expire_action :action => :show

		  #check users to make sure they match the selected client
		  selected_users = @service_user_group.users.select{|u| u.clients.include?(@service_user_group.client) }
		  puts "+++++++++++++++++++++++++"
		  puts selected_users
		  @service_user_group.users = selected_users
		  
      redirect_to([current_view, :service_user_groups], :notice => 'Technikergruppe upgedatet: ' + self.class.helpers.link_to(@service_user_group.name, admin_service_user_group_path(@service_user_group)))
    else
      render :action => "service_user_groups/edit"
    end   
  end

  def destroy
    @service_user_group = ServiceUserGroup.find(params[:id])
    @service_user_group.destroy
    #expire_action :action => :show
    redirect_to(scheduling_service_user_groups_url, :notice => 'Technikergruppe gelöscht.')
  end
end

app/helpers/service_user_groups_helper.rb
module ServiceUserGroupsHelper

end

app/views/service_user_groups/_form.html.erb
<% disabled = false unless defined?(disabled) %>

<% if @service_user_group.errors.any? %>
<%= render :partial => "general/error_messages", :locals => { :current_model => @service_user_group } %>
<% end %>

<fieldset class="group">
	<legend>Technikergruppendetails</legend>
	<div class="c">
		<%= simple_text_field(f, @service_user_group, :name, "Gruppenbezeichnung", disabled, true) %>
		<%= simple_select(f, @service_user_group, :client_id, "Mandant", current_user.clients.collect {|c| [ c.name, c.id ] }, disabled, true)  %>
		<br class="clear"/>

		<span class="left-floating-span">
			<%= f.label :postal_codes, "PLZ-Gebiete", :class => :label %>
			<%= text_area :postal_codes_csv, nil,:value => @service_user_group.postal_codes_csv, :class => "text_area", :style => "width:400px", :disabled => disabled %>
		</span>
		<span style="float:left; width:400px; margin-left:200px; margin-top:10px"> - PLZ per Komma trennen. <br/> - PLZ können mehreren Technikergruppe zugeordnet werden. </span>
		<br class="clear"/>
		<br/>
		<span class="simple_field"><%= f.label :technicians, "Techniker in dieser Gruppe", :class => :label %></span>
		<div style="float:left">
			<% ServiceUserGroup.available_service_users_for(current_user).each do |technician| %>
			<%= check_box_tag "service_user_group[user_ids][]", technician.id, @service_user_group.users.include?(technician), :disabled => disabled %> <%= link_to technician.full_name, [current_view, technician] %><br/><br/><br/>
			<% end %>
		</div>   
		<span style="float:left; width:400px; margin-left:465px; margin-top:10px"> - Techniker können mehreren Technikergruppen zugeordnet werden. <br> - Techniker können einer Technikergruppe nur zugeordnet werden, wenn sie für den gewählten Mandanten arbeiten. </span>
		<br class="clear"/><br/><br/>
	</div>
</fieldset>
<% begin %>  
<div class="navform wat-cf">
	<button class="button" type="submit">
		<%= image_tag("web-app-theme/icons/tick.png", :alt => "speichern")%> speichern
	</button>

	<% if (!@service_user_group.errors.any?) &&(params[:action] != "new") then %>
	<%= link_to image_tag("/assets/icons/cross.png", :title=>"Löschen", :alt=>"Löschen")+" löschen", [current_view, @service_user_group], :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Wirklich löschen?")}", :class=>"button" %>
	<% end %>
	<span class="text_button_padding"> oder </span>
	<%= link_to "abbrechen", [current_view, :service_user_groups], :class => "text_button_padding link_button" %>
</div>
<% end unless disabled %>

app/views/service_user_groups/_sub_menu.html.erb
<li class="first <%= params[:action]  == 'index' ? 'active' : '' %>"><%= link_to "Alle Technikergruppen", admin_service_user_groups_path %></li>
<li class="<%= params[:action] == 'new' ? 'active' : '' %>"><%= link_to "Neue Technikergruppe anlegen", new_admin_service_user_group_path %></li>
<% if params[:action] == 'edit' then %>
<li class="active"><%= link_to "Technikergruppe bearbeiten", edit_admin_service_user_group_path %></li>
<% end %>
<% if params[:action] == 'show' then %>
<li class="active"><%= link_to "Technikergruppeansicht", admin_service_user_group_path %></li>
<% end %>
<% if params[:action] == 'appointments' then %>
<li class="active"><%= link_to "Gruppenkalender", appointments_admin_service_user_group_path %></li>
<% end %>

app/views/service_user_groups/appointments.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Termine für <%= @service_user_group.name %></h2>
    <div class="inner">
      <%= render :partial => "general/calendar", :locals => { :users => @service_user_group.users, :data_url =>  "/#{current_view}/service_user_groups/#{@service_user_group.id.to_s}/appointments_data", :on_click_path => "/#{current_view}/appointments/CAL_EVENT_ID/edit", :read_only => false } %>
    </div>
  </div>
</div>

app/views/service_user_groups/appointments_data.html.erb
<%= render "general/appointments_data_per_user_group.js.erb" %>

app/views/service_user_groups/appointments_data.js.erb
<%= render "general/appointments_data_per_user_group.js" %>

app/views/service_user_groups/appointments_pop_up.html.erb
<%= render :partial => "general/calendar", :locals => { :users => @service_user_group.users, :data_url =>  "/#{current_view}/service_user_groups/#{@service_user_group.id.to_s}/appointments_data", :on_click_path => "/#{current_view}/appointments/CAL_EVENT_ID/edit", :read_only => true, :is_pop_up => true } %>

app/views/service_user_groups/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Technikergruppe bearbeiten</h2>
    <div class="inner">
      <%= form_for @service_user_group, :url => [current_view,@service_user_group], :html => { :class => :form } do |f| -%>
        <%= render :partial => "service_user_groups/form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/service_user_groups/index.html.erb
<% page_param_name ||= "page" %>
<% search_param_name ||= "q" %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">Alle Technikergruppen</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first" style="width:200px"><%= sort_link_custom search_param_name, :name, "Gruppennamen" %></th>
          <th><%= sort_link_custom search_param_name, :user, "Techniker" %></th>
          <th class="last">&nbsp;</th>
        </tr>

<% @service_user_groups.each do |service_user_group| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= link_to service_user_group.name, [current_view, service_user_group] %></td>
    <td><%= raw service_user_group.users.collect{|u| link_to(u.full_name,[current_view, u])}.join(", ") %></td>
     <td class="last">
        <%= link_to image_tag("/assets/icons/show.png", :title=>"Anzeigen", :alt=>"Anzeigen"), [current_view, service_user_group] %>
        <%= link_to image_tag("/assets/icons/date.png", :title=>"Kalender", :alt=>"Kalender"), [:appointments, current_view, service_user_group] %>
        <%= link_to image_tag("/assets/icons/edit.png", :title=>"Bearbeiten", :alt=>"Bearbeiten"), [:edit, current_view, service_user_group] if (["admin", "scheduling_leader"].include?(current_view))%>
        <%= link_to image_tag("/assets/icons/cross.png", :title=>"Löschen", :alt=>"Löschen"), [current_view, service_user_group], :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Wirklich löschen?")}" if (["admin", "scheduling_leader"].include?(current_view))%>

      </td>
  </tr>
<% end %>
</table>
<div class="navform wat-cf">
  <div class="page-entries"><%= page_entries_info %></div>
  <%= will_paginate @service_user_groups %>
</div>
<div class=" navform wat-cf">
<% if (current_view == "admin") then %>
  <a href="<%=  new_admin_service_user_group_path %>" class="button" type="submit">
    <%= image_tag("/assets/icons/user_add.png", :alt => "Technikergruppe erstellen") %> Technikergruppe erstellen
  </a>
<% end %>
</div>


    </div>
  </div>
</div>

app/views/service_user_groups/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Neue Technikergruppe</h2>
    <div class="inner">
      <%= form_for :service_user_group, :url => admin_service_user_groups_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "service_user_groups/form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/service_user_groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <%= render "sub_menu" %>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Technikergruppeansicht</h2>
    <div class="inner">
      <%= form_for @service_user_group, :url => [current_view, @service_user_group], :html => { :class => :form } do |f| -%>
        <%= render :partial => "service_user_groups/form", :locals => {:f => f, :disabled => true} %>
      <% end -%>
      <div class="navform wat-cf">
        <a class="button" href="<%= url_for([:appointments, current_view, @service_user_group]) %>">
          <%= image_tag("/assets/icons/date.png", :alt => "Kalenderansicht")%> Kalenderansicht
        </a>
        <% if (["admin", "scheduling_leader"].include?(current_view)) then %>
        <a class="button" href="<%= url_for([:edit, current_view, @service_user_group]) %>">
          <%= image_tag("/assets/icons/edit.png", :alt => "bearbeiten")%> bearbeiten
        </a>
        <% end %>
      </div>
    </div>
  </div>
</div>